{{- if .Values.dashApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dash.fullname" . }}-api
  labels:
    {{- include "dash.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.dashApi.service.type }}
  ports:
    - port: {{ .Values.dashApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.dashApi.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "dash.apiSelectorLabels" . | nindent 4 }}
{{- end }}
