{{- if .Values.dashApi.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dash.fullname" . }}-api
  labels:
    {{- include "dash.apiLabels" . | nindent 4 }}
spec:
  {{- if not .Values.dashApi.autoscaling.enabled }}
  replicas: {{ .Values.dashApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "dash.apiSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.dashApi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dash.apiSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dash.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.dashApi.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.dashApi.securityContext | nindent 12 }}
          image: "{{ .Values.dashApi.image.repository }}:{{ .Values.dashApi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dashApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dashApi.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.dashApi.service.metricsPort }}
              protocol: TCP
          env:
            - name: DATABASE_HOST
              value: {{ include "dash.fullname" . }}-postgresql
            - name: REDIS_HOST
              value: {{ include "dash.fullname" . }}-redis-master
            {{- range $key, $value := .Values.dashApi.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ include "dash.fullname" . }}-secrets
          livenessProbe:
            {{- toYaml .Values.dashApi.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.dashApi.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.dashApi.resources | nindent 12 }}
      {{- with .Values.dashApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dashApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dashApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
