{{- if .Values.dashApi.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "dash.fullname" . }}-api
  labels:
    {{- include "dash.apiLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "dash.fullname" . }}-api
  minReplicas: {{ .Values.dashApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.dashApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.dashApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.dashApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.dashApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.dashApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- with .Values.dashApi.autoscaling.metrics }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
