{{- if .Values.dashApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dash.serviceAccountName" . }}
  labels:
    {{- include "dash.labels" . | nindent 4 }}
  {{- with .Values.dashApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
