{{- if .Values.godelApi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "godel.fullname" . }}-api
  labels:
    {{- include "godel.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.godelApi.service.type }}
  ports:
    - port: {{ .Values.godelApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.godelApi.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "godel.apiSelectorLabels" . | nindent 4 }}
{{- end }}
