{{- if .Values.godelApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "godel.serviceAccountName" . }}
  labels:
    {{- include "godel.labels" . | nindent 4 }}
  {{- with .Values.godelApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
